-- Create table for tracking game sessions and live stats
CREATE TABLE IF NOT EXISTS public.game_sessions (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id text NOT NULL,
  score integer NOT NULL,
  total_questions integer NOT NULL,
  time_spent integer DEFAULT 0,
  completed boolean DEFAULT false,
  player_name text,
  created_at timestamp DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.game_sessions ENABLE ROW LEVEL SECURITY;

-- Allow anyone to view game sessions (for leaderboard)
CREATE POLICY "Anyone can view game sessions" 
ON public.game_sessions 
FOR SELECT 
USING (true);

-- Allow anyone to create game sessions
CREATE POLICY "Anyone can create game sessions" 
ON public.game_sessions 
FOR INSERT 
WITH CHECK (true);

-- Allow anyone to update their own session by session_id
CREATE POLICY "Anyone can update game sessions" 
ON public.game_sessions 
FOR UPDATE 
USING (true);

-- Enable realtime for live counter
ALTER PUBLICATION supabase_realtime ADD TABLE public.game_sessions;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_game_sessions_session_id ON public.game_sessions(session_id);